 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: ingress-service
   annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/rewrite-target: /
     certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
     nginx.ingress.kubernetes.io/ssl-redirect: 'true'
 spec:
   tls:
     - hosts:
         - antonsova.ca
         - www.antonsova.ca
       secretName: antonsova-ca
   rules:
     - host: antonsova.ca
       http:
         paths:
           - path: /
             backend:
               serviceName: server-cluster-ip-service
               servicePort: 8080
     - host: www.antonsova.ca
       http:
         paths:
           - path: /
             backend:
               serviceName: server-cluster-ip-service
               servicePort: 8080